///////////////////////////////////////////////
//   BE Trainer.NET for Red Dead Redemption 2
//               by BE.Tenner
//        Copyright (c) BE Group 2020
//                Thanks to
//   ScriptHookRdr2 & ScriptHookRdr2DotNet
//             Native Trainer
///////////////////////////////////////////////

namespace BETrainerRdr2.Model
{
    /// <summary>
    /// Model storage
    /// </summary>
    public static class ModelStorage
    {
        public static readonly ModelData[] MODELS = new ModelData[]
        {
            ModelData.Create("A_C_ALLIGATOR_01", "alligator", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_ALLIGATOR_02", "alligator 2", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_ALLIGATOR_03", "alligator 3", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_ARMADILLO_01", "armadillo", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_BADGER_01", "badger", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_BAT_01", "bat", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_BEAR_01", "bear", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_BEARBLACK_01", "bearblack", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_BEAVER_01", "beaver", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_BIGHORNRAM_01", "bighornram", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_BLUEJAY_01", "bluejay", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_BOAR_01", "boar", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_BUCK_01", "buck", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_BUFFALO_01", "buffalo", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_BULL_01", "bull", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_CALIFORNIACONDOR_01", "californiacondor", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_CARDINAL_01", "cardinal", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_CAROLINAPARAKEET_01", "carolinaparakeet", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_CAT_01", "cat", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_CEDARWAXWING_01", "cedarwaxwing", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_CHICKEN_01", "chicken", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_CHIPMUNK_01", "chipmunk", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_CORMORANT_01", "cormorant", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_COUGAR_01", "cougar", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_COW", "cow", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_COYOTE_01", "coyote", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_CRAB_01", "crab", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_CRANEWHOOPING_01", "cranewhooping", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_CROW_01", "crow", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_DEER_01", "deer", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_DOGAMERICANFOXHOUND_01", "americanfoxhound", true, false, true, false, false, false, false, false, false, false),
            ModelData.Create("A_C_DOGAUSTRALIANSHEPERD_01", "australiansheperd", true, false, true, false, false, false, false, false, false, false),
            ModelData.Create("A_C_DOGBLUETICKCOONHOUND_01", "bluetickcoonhound", true, false, true, false, false, false, false, false, false, false),
            ModelData.Create("A_C_DOGCATAHOULACUR_01", "catahoulacur", true, false, true, false, false, false, false, false, false, false),
            ModelData.Create("A_C_DOGCHESBAYRETRIEVER_01", "chesbayretriever", true, false, true, false, false, false, false, false, false, false),
            ModelData.Create("A_C_DOGCOLLIE_01", "collie", true, false, true, false, false, false, false, false, false, false),
            ModelData.Create("A_C_DOGHOBO_01", "hobo", true, false, true, false, false, false, false, false, false, false),
            ModelData.Create("A_C_DOGHOUND_01", "hound", true, false, true, false, false, false, false, false, false, false),
            ModelData.Create("A_C_DOGHUSKY_01", "husky", true, false, true, false, false, false, false, false, false, false),
            ModelData.Create("A_C_DOGLAB_01", "lab", true, false, true, false, false, false, false, false, false, false),
            ModelData.Create("A_C_DOGPOODLE_01", "poodle", true, false, true, false, false, false, false, false, false, false),
            ModelData.Create("A_C_DOGRUFUS_01", "rufus", true, false, true, false, false, false, false, false, false, false),
            ModelData.Create("A_C_DOGSTREET_01", "street", true, false, true, false, false, false, false, false, false, false),
            ModelData.Create("A_C_DONKEY_01", "donkey", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_DUCK_01", "duck", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_EAGLE_01", "eagle", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_EGRET_01", "egret", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_ELK_01", "elk", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHBLUEGIL_01_MS", "bluegil (medium)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHBLUEGIL_01_SM", "bluegil (small)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHBULLHEADCAT_01_MS", "bullheadcat (medium)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHBULLHEADCAT_01_SM", "bullheadcat (small)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHCHAINPICKEREL_01_SM", "chainpickerel (small)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHCHANNELCATFISH_01_LG", "channelcatfish (large)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHLAKESTURGEON_01_LG", "lakesturgeon (large)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHLARGEMOUTHBASS_01_LG", "largemouthbass (large)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHLARGEMOUTHBASS_01_MS", "largemouthbass (medium)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHLONGNOSEGAR_01_LG", "longnosegar (large)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHMUSKIE_01_LG", "muskie (large)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHNORTHERNPIKE_01_LG", "northernpike (large)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHPERCH_01_MS", "perch (medium)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHPERCH_01_SM", "perch (small)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHRAINBOWTROUT_01_LG", "rainbowtrout (large)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHRAINBOWTROUT_01_MS", "rainbowtrout (medium)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHREDFINPICKEREL_01_MS", "redfinpickerel (medium)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHREDFINPICKEREL_01_SM", "redfinpickerel (small)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHROCKBASS_01_MS", "rockbass (medium)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHROCKBASS_01_SM", "rockbass (small)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHSALMONSOCKEYE_01_LG", "salmonsockeye (large)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHSALMONSOCKEYE_01_MS", "salmonsockeye (medium)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHSMALLMOUTHBASS_01_LG", "smallmouthbass (large)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FISHSMALLMOUTHBASS_01_MS", "smallmouthbass (medium)", true, false, false, true, false, false, false, false, false, false),
            ModelData.Create("A_C_FOX_01", "fox", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_FROGBULL_01", "frogbull", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_GILAMONSTER_01", "gilamonster", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_GOAT_01", "goat", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_GOOSECANADA_01", "goosecanada", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HAWK_01", "hawk", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HERON_01", "heron", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_AMERICANPAINT_GREYOVERO", "americanpaint greyovero", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_AMERICANPAINT_OVERO", "americanpaint overo", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_AMERICANPAINT_SPLASHEDWHITE", "americanpaint splashedwhite", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_AMERICANPAINT_TOBIANO", "americanpaint tobiano", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_AMERICANSTANDARDBRED_BLACK", "americanstandardbred black", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_AMERICANSTANDARDBRED_BUCKSKIN", "americanstandardbred buckskin", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_AMERICANSTANDARDBRED_PALOMINODAPPLE", "americanstandardbred palominodapple", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_AMERICANSTANDARDBRED_SILVERTAILBUCKSKIN", "americanstandardbred silvertailbuckskin", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_ANDALUSIAN_DARKBAY", "andalusian darkbay", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_ANDALUSIAN_ROSEGRAY", "andalusian rosegray", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_APPALOOSA_BLANKET", "appaloosa blanket", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_APPALOOSA_BROWNLEOPARD", "appaloosa brownleopard", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_APPALOOSA_LEOPARD", "appaloosa leopard", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_APPALOOSA_LEOPARDBLANKET", "appaloosa leopardblanket", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_ARABIAN_BLACK", "arabian black", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_ARABIAN_ROSEGREYBAY", "arabian rosegreybay", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_ARABIAN_WHITE", "arabian white", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_ARDENNES_BAYROAN", "ardennes bayroan", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_ARDENNES_STRAWBERRYROAN", "ardennes strawberryroan", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_BELGIAN_BLONDCHESTNUT", "belgian blondchestnut", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_BELGIAN_MEALYCHESTNUT", "belgian mealychestnut", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_DUTCHWARMBLOOD_CHOCOLATEROAN", "dutchwarmblood chocolateroan", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_DUTCHWARMBLOOD_SEALBROWN", "dutchwarmblood sealbrown", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_DUTCHWARMBLOOD_SOOTYBUCKSKIN", "dutchwarmblood sootybuckskin", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_GANG_BILL", "gang bill", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_GANG_CHARLES", "gang charles", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_GANG_CHARLES_ENDLESSSUMMER", "gang charles endlesssummer", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_GANG_DUTCH", "gang dutch", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_GANG_HOSEA", "gang hosea", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_GANG_JAVIER", "gang javier", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_GANG_JOHN", "gang john", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_GANG_KAREN", "gang karen", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_GANG_KIERAN", "gang kieran", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_GANG_LENNY", "gang lenny", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_GANG_MICAH", "gang micah", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_GANG_SADIE", "gang sadie", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_GANG_SADIE_ENDLESSSUMMER", "gang sadie endlesssummer", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_GANG_SEAN", "gang sean", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_GANG_TRELAWNEY", "gang trelawney", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_GANG_UNCLE", "gang uncle", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_GANG_UNCLE_ENDLESSSUMMER", "gang uncle endlesssummer", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_HUNGARIANHALFBRED_DARKDAPPLEGREY", "hungarianhalfbred darkdapplegrey", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_HUNGARIANHALFBRED_FLAXENCHESTNUT", "hungarianhalfbred flaxenchestnut", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_HUNGARIANHALFBRED_PIEBALDTOBIANO", "hungarianhalfbred piebaldtobiano", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_KENTUCKYSADDLE_BLACK", "kentuckysaddle black", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_KENTUCKYSADDLE_CHESTNUTPINTO", "kentuckysaddle chestnutpinto", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_KENTUCKYSADDLE_GREY", "kentuckysaddle grey", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_KENTUCKYSADDLE_SILVERBAY", "kentuckysaddle silverbay", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_MISSOURIFOXTROTTER_AMBERCHAMPAGNE", "missourifoxtrotter amberchampagne", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_MISSOURIFOXTROTTER_SILVERDAPPLEPINTO", "missourifoxtrotter silverdapplepinto", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_MORGAN_BAY", "morgan bay", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_MORGAN_BAYROAN", "morgan bayroan", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_MORGAN_FLAXENCHESTNUT", "morgan flaxenchestnut", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_MORGAN_PALOMINO", "morgan palomino", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_MUSTANG_GRULLODUN", "mustang grullodun", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_MUSTANG_TIGERSTRIPEDBAY", "mustang tigerstripedbay", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_MUSTANG_WILDBAY", "mustang wildbay", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_NOKOTA_BLUEROAN", "nokota blueroan", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_NOKOTA_REVERSEDAPPLEROAN", "nokota reversedappleroan", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_NOKOTA_WHITEROAN", "nokota whiteroan", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_SHIRE_DARKBAY", "shire darkbay", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_SHIRE_LIGHTGREY", "shire lightgrey", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_SUFFOLKPUNCH_REDCHESTNUT", "suffolkpunch redchestnut", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_SUFFOLKPUNCH_SORREL", "suffolkpunch sorrel", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_TENNESSEEWALKER_BLACKRABICANO", "tennesseewalker blackrabicano", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_TENNESSEEWALKER_CHESTNUT", "tennesseewalker chestnut", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_TENNESSEEWALKER_DAPPLEBAY", "tennesseewalker dapplebay", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_TENNESSEEWALKER_FLAXENROAN", "tennesseewalker flaxenroan", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_TENNESSEEWALKER_REDROAN", "tennesseewalker redroan", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_THOROUGHBRED_BLOODBAY", "thoroughbred bloodbay", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_THOROUGHBRED_BRINDLE", "thoroughbred brindle", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_THOROUGHBRED_DAPPLEGREY", "thoroughbred dapplegrey", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_TURKOMAN_DARKBAY", "turkoman darkbay", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_TURKOMAN_GOLD", "turkoman gold", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSE_TURKOMAN_SILVER", "turkoman silver", true, true, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_HORSEMULE_01", "horsemule", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_IGUANA_01", "iguana", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_IGUANADESERT_01", "iguanadesert", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_JAVELINA_01", "javelina", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_LOON_01", "loon", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_MOOSE_01", "moose", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_MUSKRAT_01", "muskrat", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_ORIOLE_01", "oriole", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_OWL_01", "owl", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_OX_01", "ox", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_PANTHER_01", "panther", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_PARROT_01", "parrot", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_PELICAN_01", "pelican", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_PHEASANT_01", "pheasant", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_PIG_01", "pig", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_PIGEON", "pigeon", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_POSSUM_01", "possum", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_PRAIRIECHICKEN_01", "prairiechicken", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_PRONGHORN_01", "pronghorn", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_QUAIL_01", "quail", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_RABBIT_01", "rabbit", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_RACCOON_01", "raccoon", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_RAT_01", "rat", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_RAVEN_01", "raven", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_REDFOOTEDBOOBY_01", "redfootedbooby", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_ROBIN_01", "robin", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_ROOSTER_01", "rooster", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_ROSEATESPOONBILL_01", "roseatespoonbill", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_SEAGULL_01", "seagull", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_SHARKHAMMERHEAD_01", "sharkhammerhead", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_SHARKTIGER", "sharktiger", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_SHEEP_01", "sheep", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_SKUNK_01", "skunk", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_SNAKE_01", "snake", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_SNAKEBLACKTAILRATTLE_01", "snakeblacktailrattle", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_SNAKEFERDELANCE_01", "snakeferdelance", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_SNAKEREDBOA_01", "snakeredboa", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_SNAKEWATER_01", "snakewater", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_SONGBIRD_01", "songbird", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_SPARROW_01", "sparrow", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_SQUIRREL_01", "squirrel", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_TOAD_01", "toad", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_TURKEY_01", "turkey", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_TURKEYWILD_01", "turkeywild", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_TURTLESEA_01", "turtlesea", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_TURTLESNAPPING_01", "turtlesnapping", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_VULTURE_01", "vulture", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_WOLF", "wolf", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_WOLF_MEDIUM", "wolf medium", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_WOLF_SMALL", "wolf small", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_WOODPECKER_01", "woodpecker", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_C_WOODPECKER_02", "woodpecker 2", true, false, false, false, false, false, false, false, false, false),
            ModelData.Create("A_F_M_ARMCHOLERACORPSE_01", "armcholeracorpse", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_ARMTOWNFOLK_01", "armtownfolk", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_ARMTOWNFOLK_02", "armtownfolk 2", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_ASBTOWNFOLK_01", "asbtownfolk", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_BIVFANCYTRAVELLERS_01", "bivfancytravellers", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_BLWTOWNFOLK_01", "blwtownfolk", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_BLWTOWNFOLK_02", "blwtownfolk 2", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_BLWUPPERCLASS_01", "blwupperclass", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_BTCHILLBILLY_01", "btchillbilly", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_BTCOBESEWOMEN_01", "btcobesewomen", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_BYNFANCYTRAVELLERS_01", "bynfancytravellers", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_FAMILYTRAVELERS_WARM_01", "familytravelers warm", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_GUATOWNFOLK_01", "guatownfolk", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_HTLFANCYTRAVELLERS_01", "htlfancytravellers", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_LAGTOWNFOLK_01", "lagtownfolk", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_LOWERSDTOWNFOLK_01", "lowersdtownfolk", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_LOWERSDTOWNFOLK_02", "lowersdtownfolk 2", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_LOWERSDTOWNFOLK_03", "lowersdtownfolk 3", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_LOWERTRAINPASSENGERS_01", "lowertrainpassengers", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_MIDDLESDTOWNFOLK_01", "middlesdtownfolk", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_MIDDLESDTOWNFOLK_02", "middlesdtownfolk 2", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_MIDDLETRAINPASSENGERS_01", "middletrainpassengers", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_NBXSLUMS_01", "nbxslums", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_NBXUPPERCLASS_01", "nbxupperclass", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_NBXWHORE_01", "nbxwhore", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_RHDPROSTITUTE_01", "rhdprostitute", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_RHDTOWNFOLK_01", "rhdtownfolk", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_RHDTOWNFOLK_02", "rhdtownfolk 2", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_RHDUPPERCLASS_01", "rhdupperclass", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_RKRFANCYTRAVELLERS_01", "rkrfancytravellers", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_SCLFANCYTRAVELLERS_01", "sclfancytravellers", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_SDCHINATOWN_01", "sdchinatown", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_SDFANCYWHORE_01", "sdfancywhore", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_SDOBESEWOMEN_01", "sdobesewomen", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_SDSLUMS_02", "sdslums 2", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_STRTOWNFOLK_01", "strtownfolk", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_TUMTOWNFOLK_01", "tumtownfolk", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_TUMTOWNFOLK_02", "tumtownfolk 2", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_UPPERTRAINPASSENGERS_01", "uppertrainpassengers", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_VALPROSTITUTE_01", "valprostitute", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_VALTOWNFOLK_01", "valtownfolk", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_VHTPROSTITUTE_01", "vhtprostitute", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_VHTTOWNFOLK_01", "vhttownfolk", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_M_WAPTOWNFOLK_01", "waptownfolk", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("A_F_O_BLWUPPERCLASS_01", "blwupperclass", false, false, false, false, false, true, false, false, true, false),
            ModelData.Create("A_F_O_BTCHILLBILLY_01", "btchillbilly", false, false, false, false, false, true, false, false, true, false),
            ModelData.Create("A_F_O_GUATOWNFOLK_01", "guatownfolk", false, false, false, false, false, true, false, false, true, false),
            ModelData.Create("A_F_O_LAGTOWNFOLK_01", "lagtownfolk", false, false, false, false, false, true, false, false, true, false),
            ModelData.Create("A_F_O_SDCHINATOWN_01", "sdchinatown", false, false, false, false, false, true, false, false, true, false),
            ModelData.Create("A_F_O_SDUPPERCLASS_01", "sdupperclass", false, false, false, false, false, true, false, false, true, false),
            ModelData.Create("A_F_O_WAPTOWNFOLK_01", "waptownfolk", false, false, false, false, false, true, false, false, true, false),
            ModelData.Create("A_M_M_ARMCHOLERACORPSE_01", "armcholeracorpse", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_ARMTOWNFOLK_01", "armtownfolk", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_ARMTOWNFOLK_02", "armtownfolk 2", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_ASBMINER_01", "asbminer", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_ASBMINER_02", "asbminer 2", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_ASBMINER_03", "asbminer 3", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_ASBMINER_04", "asbminer 4", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_ASBTOWNFOLK_01", "asbtownfolk", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_BIVWORKER_01", "bivworker", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_BLWFOREMAN_01", "blwforeman", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_BLWLABORER_01", "blwlaborer", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_BLWLABORER_02", "blwlaborer 2", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_BLWOBESEMEN_01", "blwobesemen", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_BLWTOWNFOLK_01", "blwtownfolk", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_BLWUPPERCLASS_01", "blwupperclass", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_BTCHILLBILLY_01", "btchillbilly", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_BTCOBESEMEN_01", "btcobesemen", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_BYNFANCYTRAVELLERS_01", "bynfancytravellers", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_BYNROUGHTRAVELLERS_01", "bynroughtravellers", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_EMRFARMHAND_01", "emrfarmhand", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_GRIROUGHTRAVELLERS_01", "griroughtravellers", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_GUATOWNFOLK_01", "guatownfolk", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_HTLFANCYDRIVERS_01", "htlfancydrivers", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_HTLFANCYTRAVELLERS_01", "htlfancytravellers", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_HTLROUGHTRAVELLERS_01", "htlroughtravellers", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_JAMESONGUARD_01", "jamesonguard", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_LAGTOWNFOLK_01", "lagtownfolk", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_LOWERSDTOWNFOLK_01", "lowersdtownfolk", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_LOWERSDTOWNFOLK_02", "lowersdtownfolk 2", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_LOWERTRAINPASSENGERS_01", "lowertrainpassengers", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_MIDDLESDTOWNFOLK_01", "middlesdtownfolk", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_MIDDLESDTOWNFOLK_02", "middlesdtownfolk 2", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_MIDDLESDTOWNFOLK_03", "middlesdtownfolk 3", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_MIDDLETRAINPASSENGERS_01", "middletrainpassengers", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_NBXDOCKWORKERS_01", "nbxdockworkers", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_NBXLABORERS_01", "nbxlaborers", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_NBXSLUMS_01", "nbxslums", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_NBXUPPERCLASS_01", "nbxupperclass", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_NEAROUGHTRAVELLERS_01", "nearoughtravellers", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_RANCHER_01", "rancher", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_RANCHERTRAVELERS_WARM_01", "ranchertravelers warm", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_RHDFOREMAN_01", "rhdforeman", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_RHDOBESEMEN_01", "rhdobesemen", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_RHDTOWNFOLK_01", "rhdtownfolk", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_RHDTOWNFOLK_01_LABORER", "rhdtownfolk 01 laborer", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_RHDTOWNFOLK_02", "rhdtownfolk 2", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_RHDUPPERCLASS_01", "rhdupperclass", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_RKRFANCYDRIVERS_01", "rkrfancydrivers", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_RKRFANCYTRAVELLERS_01", "rkrfancytravellers", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_RKRROUGHTRAVELLERS_01", "rkrroughtravellers", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_SCLFANCYTRAVELLERS_01", "sclfancytravellers", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_SCLROUGHTRAVELLERS_01", "sclroughtravellers", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_SDCHINATOWN_01", "sdchinatown", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_SDDOCKFOREMAN_01", "sddockforeman", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_SDDOCKWORKERS_02", "sddockworkers 2", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_SDLABORERS_02", "sdlaborers 2", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_SDOBESEMEN_01", "sdobesemen", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_SDROUGHTRAVELLERS_01", "sdroughtravellers", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_SDSLUMS_02", "sdslums 2", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_SKPPRISONER_01", "skpprisoner", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_STRFANCYTOURIST_01", "strfancytourist", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_STRLABORER_01", "strlaborer", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_STRTOWNFOLK_01", "strtownfolk", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_TUMTOWNFOLK_01", "tumtownfolk", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_TUMTOWNFOLK_02", "tumtownfolk 2", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_UNIGUNSLINGER_01", "unigunslinger", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_UPPERTRAINPASSENGERS_01", "uppertrainpassengers", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_VALCRIMINALS_01", "valcriminals", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_VALFARMER_01", "valfarmer", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_VALLABORER_01", "vallaborer", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_VALTOWNFOLK_01", "valtownfolk", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_VALTOWNFOLK_02", "valtownfolk 2", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_VHTTHUG_01", "vhtthug", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_VHTTOWNFOLK_01", "vhttownfolk", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_M_WAPWARRIORS_01", "wapwarriors", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("A_M_O_BLWUPPERCLASS_01", "blwupperclass", false, false, false, false, true, false, false, false, true, false),
            ModelData.Create("A_M_O_BTCHILLBILLY_01", "btchillbilly", false, false, false, false, true, false, false, false, true, false),
            ModelData.Create("A_M_O_GUATOWNFOLK_01", "guatownfolk", false, false, false, false, true, false, false, false, true, false),
            ModelData.Create("A_M_O_LAGTOWNFOLK_01", "lagtownfolk", false, false, false, false, true, false, false, false, true, false),
            ModelData.Create("A_M_O_SDCHINATOWN_01", "sdchinatown", false, false, false, false, true, false, false, false, true, false),
            ModelData.Create("A_M_O_SDUPPERCLASS_01", "sdupperclass", false, false, false, false, true, false, false, false, true, false),
            ModelData.Create("A_M_O_WAPTOWNFOLK_01", "waptownfolk", false, false, false, false, true, false, false, false, true, false),
            ModelData.Create("A_M_Y_ASBMINER_01", "asbminer", false, false, false, false, true, false, true, false, false, false),
            ModelData.Create("A_M_Y_ASBMINER_02", "asbminer 2", false, false, false, false, true, false, true, false, false, false),
            ModelData.Create("A_M_Y_ASBMINER_03", "asbminer 3", false, false, false, false, true, false, true, false, false, false),
            ModelData.Create("A_M_Y_ASBMINER_04", "asbminer 4", false, false, false, false, true, false, true, false, false, false),
            ModelData.Create("A_M_Y_NBXSTREETKIDS_01", "nbxstreetkids", false, false, false, false, true, false, true, false, false, false),
            ModelData.Create("A_M_Y_NBXSTREETKIDS_SLUMS_01", "nbxstreetkids slums", false, false, false, false, true, false, true, false, false, false),
            ModelData.Create("A_M_Y_SDSTREETKIDS_SLUMS_02", "sdstreetkids slums 2", false, false, false, false, true, false, true, false, false, false),
            ModelData.Create("CS_ABE", "abe", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_ABERDEENPIGFARMER", "aberdeenpigfarmer", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_ABERDEENSISTER", "aberdeensister", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_ABIGAILROBERTS", "abigailroberts", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_ANGUSGEDDES", "angusgeddes", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_ARCHIEDOWN", "archiedown", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_BILLWILLIAMSON", "billwilliamson", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_BLWPHOTOGRAPHER", "blwphotographer", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_CHARLESSMITH", "charlessmith", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_CLEET", "cleet", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_CREOLECAPTAIN", "creolecaptain", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_DAVIDGEDDES", "davidgeddes", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_DOROETHEAWICKLOW", "doroetheawicklow", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_DUNCANGEDDES", "duncangeddes", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_DUTCH", "dutch", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_EAGLEFLIES", "eagleflies", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_EDITHDOWN", "edithdown", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_EDMUNDLOWRY", "edmundlowry", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_GRIZZLEDJON", "grizzledjon", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_HOSEAMATTHEWS", "hoseamatthews", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_JACKMARSTON", "jackmarston", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_JACKMARSTON_TEEN", "jackmarston teen", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_JAVIERESCUELLA", "javierescuella", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_JOE", "joe", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_JOHNMARSTON", "johnmarston", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_JOSIAHTRELAWNY", "josiahtrelawny", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_KAREN", "karen", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_KIERAN", "kieran", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_LENNY", "lenny", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_LEOSTRAUSS", "leostrauss", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_MARYBETH", "marybeth", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_MICAHBELL", "micahbell", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_MOLLYOSHEA", "mollyoshea", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_MRPEARSON", "mrpearson", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_MRSADLER", "mrsadler", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_MRSGEDDES", "mrsgeddes", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_NICHOLASTIMMINS", "nicholastimmins", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_POISONWELLSHAMAN", "poisonwellshaman", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_REVSWANSON", "revswanson", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_SDDOCTOR_01", "sddoctor", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_SEAN", "sean", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_SHERIFFFREEMAN", "sherifffreeman", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_SUSANGRIMSHAW", "susangrimshaw", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_THOMASDOWN", "thomasdown", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_TILLY", "tilly", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_TOMDICKENS", "tomdickens", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_UNCLE", "uncle", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_VALSHERIFF", "valsheriff", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("CS_WROBEL", "wrobel", false, false, false, false, false, false, false, false, false, true),
            ModelData.Create("FEMALE_SKELETON", "female skeleton", false, false, false, false, false, false, false, false, false, false),
            ModelData.Create("G_M_M_UNIBANDITOS_01", "unibanditos", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("G_M_M_UNIBRAITHWAITES_01", "unibraithwaites", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("G_M_M_UNIBRONTEGOONS_01", "unibrontegoons", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("G_M_M_UNICORNWALLGOONS_01", "unicornwallgoons", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("G_M_M_UNICRIMINALS_01", "unicriminals", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("G_M_M_UNICRIMINALS_02", "unicriminals 2", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("G_M_M_UNIDUSTER_01", "uniduster", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("G_M_M_UNIDUSTER_02", "uniduster 2", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("G_M_M_UNIDUSTER_03", "uniduster 3", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("G_M_M_UNIGRAYS_01", "unigrays", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("G_M_M_UNIINBRED_01", "uniinbred", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("G_M_M_UNIMOUNTAINMEN_01", "unimountainmen", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("G_M_O_UNIEXCONFEDS_01", "uniexconfeds", false, false, false, false, true, false, false, false, true, false),
            ModelData.Create("G_M_Y_UNIEXCONFEDS_01", "uniexconfeds", false, false, false, false, true, false, true, false, false, false),
            ModelData.Create("PLAYER_THREE", "player three", false, false, false, false, false, false, false, false, false, false),
            ModelData.Create("PLAYER_ZERO", "player zero", false, false, false, false, false, false, false, false, false, false),
            ModelData.Create("RCSP_CALDERON_MALES_01", "rcsp calderon males 01", false, false, false, false, false, false, false, false, false, false),
            ModelData.Create("RE_DEADBODIES_MALES_01", "re deadbodies males 01", false, false, false, false, false, false, false, false, false, false),
            ModelData.Create("S_F_M_BWMWORKER_01", "bwmworker", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("S_F_M_CGHWORKER_01", "cghworker", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("S_F_M_MAPWORKER_01", "mapworker", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("S_M_M_AMBIENTBLWPOLICE_01", "ambientblwpolice", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_AMBIENTLAWRURAL_01", "ambientlawrural", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_AMBIENTSDPOLICE_01", "ambientsdpolice", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_ARMY_01", "army", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_BANKCLERK_01", "bankclerk", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_BARBER_01", "barber", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_BLWCOWPOKE_01", "blwcowpoke", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_BWMWORKER_01", "bwmworker", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_CGHWORKER_01", "cghworker", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_CKTWORKER_01", "cktworker", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_CORNWALLGUARD_01", "cornwallguard", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_FUSSARHENCHMAN_01", "fussarhenchman", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_LIVERYWORKER_01", "liveryworker", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_MAGICLANTERN_01", "magiclantern", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_MAPWORKER_01", "mapworker", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_MARKETVENDOR_01", "marketvendor", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_RACRAILGUARDS_01", "racrailguards", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_RACRAILWORKER_01", "racrailworker", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_RHDCOWPOKE_01", "rhdcowpoke", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_SDCOWPOKE_01", "sdcowpoke", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_SDTICKETSELLER_01", "sdticketseller", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_SKPGUARD_01", "skpguard", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_STRLUMBERJACK_01", "strlumberjack", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_TAILOR_01", "tailor", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_TRAINSTATIONWORKER_01", "trainstationworker", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_TUMDEPUTIES_01", "tumdeputies", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_UNIBUTCHERS_01", "unibutchers", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_UNITRAINENGINEER_01", "unitrainengineer", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_UNITRAINGUARDS_01", "unitrainguards", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_M_VALCOWPOKE_01", "valcowpoke", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("S_M_Y_ARMY_01", "army", false, false, false, false, true, false, true, false, false, false),
            ModelData.Create("S_M_Y_NEWSPAPERBOY_01", "newspaperboy", false, false, false, false, true, false, true, false, false, false),
            ModelData.Create("S_M_Y_RACRAILWORKER_01", "racrailworker", false, false, false, false, true, false, true, false, false, false),
            ModelData.Create("U_F_M_HTLWIFE_01", "htlwife", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("U_F_M_LAGMOTHER_01", "lagmother", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("U_F_M_RKSHOMESTEADTENANT_01", "rkshomesteadtenant", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("U_F_M_TUMGENERALSTOREOWNER_01", "tumgeneralstoreowner", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("U_F_M_VHTBARTENDER_01", "vhtbartender", false, false, false, false, false, true, false, true, false, false),
            ModelData.Create("U_F_O_WTCTOWNFOLK_01", "wtctownfolk", false, false, false, false, false, true, false, false, true, false),
            ModelData.Create("U_F_Y_CZPHOMESTEADDAUGHTER_01", "czphomesteaddaughter", false, false, false, false, false, true, true, false, false, false),
            ModelData.Create("U_M_M_ARMGENERALSTOREOWNER_01", "armgeneralstoreowner", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_ARMTRAINSTATIONWORKER_01", "armtrainstationworker", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_ARMUNDERTAKER_01", "armundertaker", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_ASBGUNSMITH_01", "asbgunsmith", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_BIVFOREMAN_01", "bivforeman", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_BLWTRAINSTATIONWORKER_01", "blwtrainstationworker", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_BWMSTABLEHAND_01", "bwmstablehand", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_CAJHOMESTEAD_01", "cajhomestead", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_CRDHOMESTEADTENANT_01", "crdhomesteadtenant", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_CRDHOMESTEADTENANT_02", "crdhomesteadtenant 2", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_CZPHOMESTEADFATHER_01", "czphomesteadfather", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_DORHOMESTEADHUSBAND_01", "dorhomesteadhusband", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_EMRFATHER_01", "emrfather", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_HHRRANCHER_01", "hhrrancher", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_HTLFOREMAN_01", "htlforeman", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_HTLHUSBAND_01", "htlhusband", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_LNSWORKER_01", "lnsworker", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_LNSWORKER_02", "lnsworker 2", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_LNSWORKER_03", "lnsworker 3", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_LNSWORKER_04", "lnsworker 4", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_LRSHOMESTEADTENANT_01", "lrshomesteadtenant", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_MFRRANCHER_01", "mfrrancher", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_NBXBARTENDER_01", "nbxbartender", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_NBXBARTENDER_02", "nbxbartender 2", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_NBXGENERALSTOREOWNER_01", "nbxgeneralstoreowner", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_NBXGUNSMITH_01", "nbxgunsmith", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_NBXSHADYDEALER_01", "nbxshadydealer", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_ORPGUARD_01", "orpguard", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_RACFOREMAN_01", "racforeman", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_RHDBARTENDER_01", "rhdbartender", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_RHDGENSTOREOWNER_01", "rhdgenstoreowner", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_RHDGENSTOREOWNER_02", "rhdgenstoreowner 2", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_RHDGUNSMITH_01", "rhdgunsmith", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_RHDSHERIFF_01", "rhdsheriff", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_RHDTRAINSTATIONWORKER_01", "rhdtrainstationworker", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_RKFRANCHER_01", "rkfrancher", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_SDPHOTOGRAPHER_01", "sdphotographer", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_SDPOLICECHIEF_01", "sdpolicechief", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_SDTRAPPER_01", "sdtrapper", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_STRFREIGHTSTATIONOWNER_01", "strfreightstationowner", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_STRGENSTOREOWNER_01", "strgenstoreowner", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_STRSHERRIFF_01", "strsherriff", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_STRWELCOMECENTER_01", "strwelcomecenter", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_TUMBARTENDER_01", "tumbartender", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_TUMBUTCHER_01", "tumbutcher", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_TUMGUNSMITH_01", "tumgunsmith", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_UNIEXCONFEDSBOUNTY_01", "uniexconfedsbounty", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_VALBARBER_01", "valbarber", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_VALBARTENDER_01", "valbartender", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_VALBUTCHER_01", "valbutcher", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_VALDOCTOR_01", "valdoctor", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_VALGENSTOREOWNER_01", "valgenstoreowner", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_VALGUNSMITH_01", "valgunsmith", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_VALHOTELOWNER_01", "valhotelowner", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_VHTSTATIONCLERK_01", "vhtstationclerk", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_WALGENERALSTOREOWNER_01", "walgeneralstoreowner", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_M_WAPOFFICIAL_01", "wapofficial", false, false, false, false, true, false, false, true, false, false),
            ModelData.Create("U_M_O_ARMBARTENDER_01", "armbartender", false, false, false, false, true, false, false, false, true, false),
            ModelData.Create("U_M_O_ASBSHERIFF_01", "asbsheriff", false, false, false, false, true, false, false, false, true, false),
            ModelData.Create("U_M_O_BLWBARTENDER_01", "blwbartender", false, false, false, false, true, false, false, false, true, false),
            ModelData.Create("U_M_O_BLWGENERALSTOREOWNER_01", "blwgeneralstoreowner", false, false, false, false, true, false, false, false, true, false),
            ModelData.Create("U_M_O_BLWPOLICECHIEF_01", "blwpolicechief", false, false, false, false, true, false, false, false, true, false),
            ModelData.Create("U_M_O_CAJHOMESTEAD_01", "cajhomestead", false, false, false, false, true, false, false, false, true, false),
            ModelData.Create("U_M_O_CMRCIVILWARCOMMANDO_01", "cmrcivilwarcommando", false, false, false, false, true, false, false, false, true, false),
            ModelData.Create("U_M_O_PSHRANCHER_01", "pshrancher", false, false, false, false, true, false, false, false, true, false),
            ModelData.Create("U_M_O_VALBARTENDER_01", "valbartender", false, false, false, false, true, false, false, false, true, false),
            ModelData.Create("U_M_O_VHTEXOTICSHOPKEEPER_01", "vhtexoticshopkeeper", false, false, false, false, true, false, false, false, true, false),
            ModelData.Create("U_M_Y_CAJHOMESTEAD_01", "cajhomestead", false, false, false, false, true, false, true, false, false, false),
            ModelData.Create("U_M_Y_CZPHOMESTEADSON_01", "czphomesteadson", false, false, false, false, true, false, true, false, false, false),
            ModelData.Create("U_M_Y_CZPHOMESTEADSON_02", "czphomesteadson 2", false, false, false, false, true, false, true, false, false, false),
            ModelData.Create("U_M_Y_CZPHOMESTEADSON_03", "czphomesteadson 3", false, false, false, false, true, false, true, false, false, false),
            ModelData.Create("U_M_Y_EMRSON_01", "emrson", false, false, false, false, true, false, true, false, false, false),
            ModelData.Create("U_M_Y_HTLWORKER_01", "htlworker", false, false, false, false, true, false, true, false, false, false),
            ModelData.Create("U_M_Y_HTLWORKER_02", "htlworker 2", false, false, false, false, true, false, true, false, false, false),
        };
    }
}
