///////////////////////////////////////////////
//   BE Trainer.NET for Red Dead Redemption 2
//               by BE.Tenner
//        Copyright (c) BE Group 2020
//                Thanks to
//   ScriptHookRdr2 & ScriptHookRdr2DotNet
//             Native Trainer
///////////////////////////////////////////////

namespace BETrainerRdr2.Vehicle
{
	/// <summary>
	/// Vehicle storage
	/// </summary>
	public static class VehicleStorage
    {
        public static readonly string[] VEHICLE_MODELS = new string[] 
        {
			"privateopensleeper02x",
			"privateopensleeper01x",
			"STEAMERDUMMY",
			"armoredCar01x",
			"armoredCar03x",
			"privatebaggage01x",
			"smuggler02",
			"keelboat",
			"boatSteam02x",
			"midlandrefrigeratorCar",
			"midlandboxcar05x",
			"CABOOSE01X",
			"canoe",
			"canoeTreeTrunk",
			"cart01",
			"cart02",
			"cart03",
			"cart04",
			"cart05",
			"cart06",
			"cart07",
			"cart08",
			"coach2",
			"coach3",
			"coach3",
			"coach4",
			"coach5",
			"coach6",
			"cart06",
			"cart06",
			"buggy03",
			"ArmySupplyWagon",
			"chuckwagon000x",
			"chuckwagon000x",
			"chuckwagon000x",
			"logwagon",
			"logwagon2",
			"coal_wagon",
			"chuckwagon002x",
			"gatling_gun",
			"gatlingMaxim02",
			"handcart",
			"horseBoat",
			"hotAirBalloon01",
			"hotchkiss_cannon",
			"mineCart01x",
			"northflatcar01x",
			"privateflatcar01x",
			"northpassenger01x",
			"northpassenger03x",
			"privatepassenger01x",
			"oilWagon01x",
			"oilWagon02x",
			"pirogue",
			"pirogue2",
			"policeWagon01x",
			"policeWagongatling01x",
			"privateCoalCar01x",
			"NorthCoalCar01x",
			"winterSteamer",
			"wintercoalcar",
			"privateboxcar04x",
			"privateboxcar02x",
			"privateboxcar01x",
			"coalHopper01x",
			"privateObservationcar",
			"privateArmoured",
			"privateDining01x",
			"privateRooms01x",
			"privateSteamer01x",
			"northSteamer01x",
			"GhostTrainSteamer",
			"GhostTrainCoalCar",
			"GhostTrainPassenger",
			"GhostTrainCaboose",
			"rcBoat",
			"rowboat",
			"rowboatSwamp",
			"rowboatSwamp02",
			"ship_guama02",
			"turbineboat",
			"ship_nbdGuama",
			"ship_nbdGuama2",
			"skiff",
			"stagecoach001x",
			"stagecoach002x",
			"stagecoach003x",
			"STAGECOACH004X",
			"stagecoach001x",
			"stagecoach006x",
			"TROLLEY01X",
			"TugBoat2",
			"wagon02x",
			"wagon03x",
			"wagon04x",
			"wagon05x",
			"wagon06x",
			"wagonCircus01x",
			"wagonCircus02x",
			"wagonDoc01x",
			"wagonPrison01x",
			"wagonWork01x",
			"wagonDairy01x",
			"wagonTraveller01x",
			"breach_cannon",
			"utilliwag",
			"gatchuck",
			"gatchuck_2",
		};
    }
}
